# Generated by Django 3.0.6 on 2020-06-01 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news_board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="upvotes", new_name="upvote",
        ),
        migrations.AlterField(
            model_name="upvote",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upvotes",
                to="news_board.Post",
            ),
        ),
    ]
